### ISSUE TITLE
i18n for translations?

### ISSUE THREAD

**Issue by kalininskiy** [no-stack-dub-sack/cs-playground-react#15]

**Comment by no-stack-dub-sack** [comment]
@kalininskiy it's a great idea, can it be used outside of express? I've just taken a look at the docs and it looks like it might be closely coupled with express, but not sure. I'm open to it, but am a bit bogged down with another project at the moment. Would you be interested in making a PR? If so, I would totally work with you and accept it if we can figure out a way to offer translations seamlessly!
