### ISSUE TITLE
Can't edit any seed or solution information

### ISSUE THREAD

**Issue by oliverfencott** [no-stack-dub-sack/cs-playground-react#16]
Hello,

When I change any seed or solution information in the exported file (e.g. `src/assets/seed/data-structures/LinkedList.js` ), no changes are reflected in the UI. However, when I change the title string or resources array, the changes are made.

I've cleared my local storage, not really sure of what else to try (or why this might be happening), any ideas?

Thanks!

**Comment by no-stack-dub-sack** [comment]
@oliverfencott hmmm... yes, just another good reason for me to add a contributing doc (#18).

Try leaving a `// DO NOT SAVE` comment anywhere in the editor before navigating away from the page (just x out the tab). Then save your changes and reload. Let me know if this works. Though normally, when I make changes, just clearing local storage has done it for me. 

There are definitely some pitfalls to the local storage approach, and I guess this is one of them. 

If this doesn't work, let me know, and we can try a screen share at some point to figure it out.

**Comment by no-stack-dub-sack** [comment]
@oliverfencott closing as stale - feel free to reopen if you still need help with this
