### ISSUE TITLE
Error (stack exhausted, infinite loop, reference error etc.) silences console.log

### ISSUE THREAD

**Issue by btruhand** [no-stack-dub-sack/cs-playground-react#48]
When an error is caught it seems that user defined ```console.log``` statements are rendered mute. That is:

```javascript
function infinite() {
  console.log("This won't be shown in console");
  while (true) {}
}

infinite();
```

Running the above would cause the console statement to not display the string. Instead you will only get:
```
Error: Timed out after 500ms due to infinite loop on line 3
```

Having console log statements can be very helpful during any sort of quick debugging

**Comment by no-stack-dub-sack** [comment]
Oh, and this should only be for infinite loops, when other errors are caught, it should still log any messages prior to the error stopping exection of the code
