### ISSUE TITLE
[staging]: add user created repls

### ISSUE THREAD

**Issue by no-stack-dub-sack** [no-stack-dub-sack/cs-playground-react#60]
Allow users to add their own repls to app state for jotting down their own ideas, algos, problems, test things out, etc.

Also: in new feature branch, identify source of issue when refreshing the page on a newly created repl before switching challenges. 

__FIXED:__ Should also switch to new repl when created.

**Comment by mansisce** [comment]
Please provide steps to reproduce the same

**Comment by no-stack-dub-sack** [comment]
@mansisce sorry, I should have specified. This is an issue with a new feature I'm developing which has not yet been deployed. I am working on fixing this on the feature branch before merging. Thanks!
