### ISSUE TITLE
add hamburger menu and keybindings modal

### ISSUE THREAD

**Issue by no-stack-dub-sack** [no-stack-dub-sack/cs-playground-react#73]
@mansisce here's the last feature I want to implement before pushing all this new code to production. With all these new features (especially including the last big update) there are a ton of new key bindings (for the editor and for the app itself) that I'm afraid people won't know about, since they are only talked about on the welcome screen and in the docs (for example, did you know you could change themes <kbd>CMD/CTRL</kbd>+<kbd>ALT</kbd>+<kbd>{</kbd> OR <kbd>}</kbd>?).

I would love to add a hamburger menu in place of the current share link button: 

![image](https://user-images.githubusercontent.com/18563015/37245240-3079f576-2463-11e8-87b0-420648739e3a.png)

When expanded, the hamburger menu could include a "Get Share Link" button (either icon or text), which would have the same behavior as the current button, and a "View Key Bindings" button, which would open a modal that listed all the applications key bindings including all those listed below. This would also give us a place to eventually add additional links, such as the "Settings" menu (#65), which would link to a different route.

Is this something you would be interested in taking on? No worries if not, but thought I'd ask before I jumped in! If so, the latest code is on the staging branch, not master, so you'd have to pull that down.

***
## Key Bindings / Application Shortcut Keys:
- The editor has SublimeText keybindings.
- Additional keys bindings / shortcuts:
  - Scroll through themes: <kbd>CMD/CTRL</kbd>+<kbd>ALT</kbd>+(<kbd>{</kbd> OR <kbd>}</kbd>)
  - Go to the next challenge: <kbd>CMD/CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>.</kbd>
  - Go to the previous challenge: <kbd>CMD/CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>,</kbd>
  - Jump to solution / seed: <kbd>CMD/CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>S</kbd>
  - Run code / tests: <kbd>CMD/CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>ENTER</kbd>
  - Toggle Suppress Tests: <kbd>CMD/CTRL</kbd>+<kbd>ALT</kbd>+<kbd>/</kbd>
  - Clear Console: <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>DELTE/BACKSPACE</kbd>
  - Open autocomplete dropdown: <kbd>CTRL</kbd>+<kbd>SPACE</kbd>
  - Focus Editor: <kbd>CMD/CTRL</kbd>+<kbd>\\</kbd>
- Search / Replace functionalities:
  - Start searching: <kbd>CMD/CTRL</kbd>+<kbd>F</kbd>
  - Find next: <kbd>CMD/CTRL</kbd>+<kbd>G</kbd>
  - Find previous: <kbd>CMD/CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>G</kbd>
  - Replace: <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd> OR <kbd>SHIFT</kbd>+<kbd>CTRL</kbd>+<kbd>F</kbd>
  - Replace all: <kbd>SHIFT</kbd>+<kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd> OR <kbd>SHIFT</kbd>+<kbd>CTRL</kbd>+<kbd>R</kbd>
  - Jump to line: <kbd>ALT</kbd>+<kbd>G</kbd>

**Comment by mansisce** [comment]
> Is this something you would be interested in taking on? No worries if not, but thought I'd ask before I jumped in! If so, the latest code is on the staging branch, not master, so you'd have to pull that down.

Yes, i like to take this up.

**Comment by mansisce** [comment]
@no-stack-dub-sack I'm wondering I don't see this button as mentioned below

> I would love to add a hamburger menu in place of the current share link button:

**Comment by mansisce** [comment]
> (for example, did you know you could change themes CMD/CTRL+ALT+{ OR }?).

No, I was not knowing this. There are so many themes i can choose from. Simply awesome!

**Comment by no-stack-dub-sack** [comment]
@mansisce Glad you like the themes! And this is a perfect example of why we need this feature :smile: 

If you don't see the share button, it's probably because you need to check out and pull down the staging branch (the master branch does not reflect the current deployment on https://cs-playground-react.surge.sh but it is behind the staging branch by several commits, most of the changes on the staging branch are deployed at https://questionable-number.surge.sh which is just a test deployment to test out new changes).

I'm open to suggestions about where the menu goes, but if we put it there, I'd want to leave the share button where it is, meaning the only item in the hamburger menu for the time being would be the key bindings modal button. Which is fine, we can add more to it later, when more items become available.

The main "Contents" menu, I think should remain where it is, rather than inside the hamburger menu, otherwise, that space would be very empty when the menu was completely closed.

Maybe before the logic actually gets implemented, you can post a screen shot of what it would look like the way you are currently picturing it, and we can decide from there. What do you think?

Thanks again for your help!

**Comment by mansisce** [comment]
@no-stack-dub-sack I am going with your suggestion as of now. Please find the rough screenshot attached.  Let me know if that is fine with you.
Note: This is WIP screenshot.


![screen shot 2018-03-14 at 12 56 22 am](https://user-images.githubusercontent.com/5550539/37365129-9a38f8e2-2722-11e8-8dca-f8f55a25016b.jpg)

**Comment by no-stack-dub-sack** [comment]
@mansisce that's perfect! let's use the `Menu` icon component from React feather, and instead of a bulleted list, lets match the style of the sidebar menu a bit more and just do something closer to this:

https://codepen.io/no_stack_dub_sack/pen/wmMXaM

There doesn't even need to be inner borders if that looks better. Just stacked icons / words in a fixed width box, with highlight on hover effects that match the menu to the side. 

Let me know how you make out! Sorry there's such a delay between our communications, we must be on different time zones, though if you reach me on Gitter I may be able to communicate during work when you're usually online. Do you use Gitter at all? If so, we might be able to shorten the feedback loop so we don't have to slow things down...

**Comment by no-stack-dub-sack** [comment]
@mansisce also, just so you know, I'm going on holiday starting this Friday, and I won't be back until the 26th, so I probably won't be around as much, but I will do my best to check in on this when I can. I'm really looking forward to seeing what you come up with!

**Comment by mansisce** [comment]
@no-stack-dub-sack <https://github.com/no-stack-dub-sack> sorry for the
huge delay is the response. I was very busy with office work. I have a
couple of days time now. If this is not done then I will continue.

Yes, I do have Gitter account. I have just pinged you there.

Do you use Gitter at all? If so, we might be able to shorten the feedback
loop so we don't have to slow things down...

**Comment by no-stack-dub-sack** [comment]
@mansisce no worries at all! I've been away until now anyway, so nothing has gotten done on my end. It's yours if you still want it, but no pressure, only if you have the time and are excited about it :smile:
